### ISSUE TITLE
add mock data

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore-component-library#7]
## summary
we'd like to simulate the components interacting with data from the api

## resources
- https://storybook.js.org/docs/react/writing-stories/build-pages-with-storybook#mocking-connected-components

**Comment by alishaevn** [comment]
the mock data we're using is in each components story, instead of building out a page that renders multiple components. this practice can be seen in places like the [status bar stories](https://github.com/scientist-softserv/webstore-component-library/blob/main/src/components/StatusBar/StatusBar.stories.jsx).
